[alias]
# compute test coverage of the crate and output into html and xml format
coverage-unit = [
    "tarpaulin",
    "--workspace",
    "--exclude-files", "tests/*",   # Exclude integration test code
    "--out", "Html",
    "--lib"
]
coverage-integration = [
    "tarpaulin",
    "--workspace",
    "--exclude-files", "tests/*",
    "--out", "Html",
    "--engine", "llvm",
    "--test", "integration_tests"
]

# Apply rust formatting throughout project [run with `cargo +nightly` to also re-order imports etc]
fmt-all = "fmt --all"

# Generate crate documentation correctly rendering all mathematics
doc-math = "doc --features doc-math"

# Run the CI commands to locally check that they will pass/fail.
clippy-ci = "clippy --all-features -- -D warnings"
fmt-ci = "fmt --all -- --check"